all:
  datagrid:
    images_dir: /sfDatagridPlugin/img/
    class_for_foreign: sfWidgetFormPropelSelect # Or sfWidgetFormDoctrineSelect  
    
    text_novalueinrows: Rien dans cette liste
    text_search: Rechercher
    text_reset: Réinitialiser 
    text_validate: Valider
    text_page: Page
    text_defaultview: Vue par défaut
    text_numberofrecords: Nombre d'enregistrement
    text_loading: Veuillez patienter
    text_from: Du
    text_to: Au